[package]
name = "nes_emul"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nes_emul"
path = "src/main.rs"

[lib]
name = "nes_emul"
path = "src/lib.rs"

[dependencies]
cast = "0.3.0"
sdl2 = "0.34.0"
rand = "=0.7.3"